environment:
  nodejs_version: "7"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --loglevel=error # no warnings
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run build

# Don't actually build.
build: off